server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:32768/paymentdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0